feat: add missing network implementations for Darwin platforms
wireapp/kalium pull request #1319
Opened 2023-01-10 16:37 UTC by typfel

----
#### PR Submission Checklist for internal contributors

- The **PR Title**
  - [ ] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
  - [ ] contains a reference JIRA issue number like `SQPIT-764`
  - [ ] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
  - [ ] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

- Fix issue with access cookie not being parsed correctly on iOS/macOS due to a case sensitivity issue
- Add missing implementation of the `provideEnvelopeProtoMapper`

### Testing

#### Test Coverage (Optional)

- [x] I have added automated test to this contribution

### Notes

Only `OtrUserIdMapper` uses iOS specific classes. We find a way to parse/encode UUIDs using common code we could move the whole `provideEnvelopeProtoMapper` into common.

----
#### PR Post Submission Checklist for internal contributors (Optional)

 - [ ] Wire's Github Workflow has automatically linked the PR to a JIRA issue
----
#### PR Post Merge Checklist for internal contributors

 - [ ] If any soft of configuration variable was introduced by this PR, it has been added to the relevant documents and the CI jobs have been updated.
----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

2023-01-10 16:39 UTC, typfel commented on network/src/commonMain/kotlin/com/wire/kalium/network/utils/NetworkResponse.kt
> +                .mapKeys { headerEntry -> headerEntry.key.lowercase() }
Comments around this code suggests we should stop exposing `headers` and `cookies` on `NetworkResponse` so maybe we should use KTORs header/cookie API directly which is case insensitive.

2023-01-10 16:56 UTC, vitorhugods requested changes
Nice 😍

We could still bring the Android/JVM and Darwin implementation closer by writing a single `EnvelopeProtoMapper`, and just having an `expect`/`actual` for the `UserIdMapper`.

So instead of having a `provideEnvelopeProtoMapper`, we just need a `provideUserIdProtoMapper`.

2023-01-11 12:13 UTC, vitorhugods approved these changes
Great 🙌🏼

I've noticed that all of these mappers could be internal actually. But it doesn't need to be fixed in this PR, is was already public before.

2023-01-11 12:13 UTC, vitorhugods commented on network/src/commonMain/kotlin/com/wire/kalium/network/api/base/authenticated/message/EnvelopeProtoMapper.kt
> +class EnvelopeProtoMapperImpl : EnvelopeProtoMapper {
This can be `internal`

2023-01-11 12:13 UTC, vitorhugods commented on network/src/darwinMain/kotlin/com/wire/kalium/network/api/base/authenticated/message/OtrUserIdMapper.kt
> +class OtrUserIdMapperImpl: OtrUserIdMapper {
Same here

2023-01-12 16:52 UTC, merged