fix: Synchronize crypto operations execution (#1378)
wireapp/kalium pull request #1396
Opened 2023-01-25 02:09 UTC by MohamadJaara

* synchronize crypto session operation

* chore: execute crypto functions on default context

* add TODO

* chore: use default dispatcher in non IO operations

* chore: cleanup

* chore: fix build

* chore: cleanup

* chore: cleanup

* chore: formatting

* chore: fix build

* chore: make currentSession method suspend on other platforms

* chore: formatting

* fix: calling suspend function inside a coroutine scope

* chore: remove suspend modifier

* fix: remove empty lines

* fix: nullable fields

* fix: update test to use suspendFunction

* chore: nullable fields

* chore: suspend modifier

* chore: use standardScope

* chore: missing params for jvm sample

* chore: remove unused imports

* synchronize crypto box operations

* fix tests

* styling

* add exception cause to logs

* styling

* styling

* remove replace limitedParallelism with a Mutex

* styling

* missing lock on deleteSession

* fix samples

Co-authored-by: Oussama <oussama.has100@gmail.com>
Co-authored-by: Tommaso Piazza <196761+tmspzz@users.noreply.github.com>
Co-authored-by: Mojtaba Chenani <chenani@outlook.com>

----
#### PR Submission Checklist for internal contributors

- The **PR Title**
  - [ ] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
  - [ ] contains a reference JIRA issue number like `SQPIT-764`
  - [ ] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
  - [ ] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

### Issues

_Briefly describe the issue you have solved or implemented with this pull request. If the PR contains multiple issues, use a bullet list._

### Causes (Optional)

_Briefly describe the causes behind the issues. This could be helpful to understand the adopted solutions behind some nasty bugs or complex issues._

### Solutions

_Briefly describe the solutions you have implemented for the issues explained above._

### Dependencies (Optional)

_If there are some other pull requests related to this one (e.g. new releases of frameworks), specify them here._

Needs releases with:

- [ ] GitHub link to other pull request

### Testing

#### Test Coverage (Optional)

- [ ] I have added automated test to this contribution

#### How to Test

_Briefly describe how this change was tested and if applicable the exact steps taken to verify that it works as expected._

### Notes (Optional)

_Specify here any other facts that you think are important for this issue._

### Attachments (Optional)

_Attachments like images, videos, etc. (drag and drop in the text box)_

----
#### PR Post Submission Checklist for internal contributors (Optional)

 - [ ] Wire's Github Workflow has automatically linked the PR to a JIRA issue
----
#### PR Post Merge Checklist for internal contributors

 - [ ] If any soft of configuration variable was introduced by this PR, it has been added to the relevant documents and the CI jobs have been updated.
----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

2023-01-25 02:11 UTC, MohamadJaara commented on cryptography/src/iosX64Main/kotlin/com/wire/kalium/cryptography/ProteusClientImpl.kt
> +
Should this file be deleted?

2023-01-25 13:54 UTC, typfel requested changes

2023-01-25 13:54 UTC, typfel commented on cryptography/src/darwinTest/kotlin/com/wire/kalium/cryptography/BaseProteusClientTest.kt
> +        return ProteusClientImpl(proteusStore.value, defaultContext = standardScope, ioContext = standardScope)
This you lost the `ProteusDBSecret("secret")`. Darwin only supports encrypted proteus storage so the tests will always fail now.

2023-02-02 09:09 UTC, typfel approved these changes

2023-02-02 09:09 UTC, merged