feat(e2ei): add networking layer for acme server
wireapp/kalium pull request #1625
Opened 2023-04-11 08:57 UTC by mchenani

----
#### PR Submission Checklist for internal contributors

- The **PR Title**
  - [x] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
  - [ ] contains a reference JIRA issue number like `SQPIT-764`
  - [x] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
  - [ ] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?
* Networking layer for ACME server
* Add ignoreSSLCert option to httpClient [this is only enabled for development staging]
### Issues

The current ACME server is a test server without a valid SSL cert.
----
#### PR Post Submission Checklist for internal contributors (Optional)

 - [ ] Wire's Github Workflow has automatically linked the PR to a JIRA issue
----
#### PR Post Merge Checklist for internal contributors

 - [ ] If any soft of configuration variable was introduced by this PR, it has been added to the relevant documents and the CI jobs have been updated.
----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

2023-04-11 10:20 UTC, mchenani commented on network/src/commonJvmAndroid/kotlin/com/wire/kalium/network/HttpEngine.kt
> +        OkHttpClient.Builder().ignoreAllSSLErrors().pingInterval(WEBSOCKET_PING_INTERVAL_MILLIS, TimeUnit.MILLISECONDS)
Oh, thanks. fixing it.

2023-04-17 16:23 UTC, typfel requested changes

2023-04-17 16:23 UTC, typfel commented on network/src/commonMain/kotlin/com/wire/kalium/network/api/base/authenticated/e2ei/E2EIApi.kt
> +    suspend fun sendAuthzClienId(): NetworkResponse<Unit>
```suggestion
    suspend fun sendAuthzClientId(): NetworkResponse<Unit>
```

2023-04-17 16:23 UTC, typfel commented on network/src/commonMain/kotlin/com/wire/kalium/network/api/base/authenticated/e2ei/E2EIApi.kt
> +        fun getApiNotSupportError(apiName: String, apiVersion: String = "4") = NetworkResponse.Error(
Nice, don't have to solve it now but would it possible to share this function with all API interfaces? Move it to a base API interface?

2023-04-17 16:23 UTC, typfel commented on logic/src/commonMain/kotlin/com/wire/kalium/logic/featureFlags/KaliumConfigs.kt
> +    val ignoreAllSSLErrors: Boolean = false,
So will this be removed once we have more proper development setup?

2023-05-02 10:37 UTC, closed without merging