feat: offline backends - users metadata (AR-3123)
wireapp/kalium pull request #1698
Opened 2023-05-05 09:47 UTC by yamilmedina

----
#### PR Submission Checklist for internal contributors

- The **PR Title**
  - [x] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
  - [x] contains a reference JIRA issue number like `SQPIT-764`
  - [x] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
  - [x] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

### Issues

We need to support displaying/ hiding and restrict options for users that we don't have metadata for.
This is done in, other user profile, participants lists and conversations list.

### Solutions

Adjust query to hide conversations for users without metadata

### Testing

#### Test Coverage (Optional)

- [ ] I have added automated test to this contribution

----
#### PR Post Submission Checklist for internal contributors (Optional)

 - [ ] Wire's Github Workflow has automatically linked the PR to a JIRA issue
----
#### PR Post Merge Checklist for internal contributors

 - [x] If any soft of configuration variable was introduced by this PR, it has been added to the relevant documents and the CI jobs have been updated.
----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

2023-05-09 12:30 UTC, MohamadJaara commented on persistence/src/commonMain/db_user/com/wire/kalium/persistence/Conversations.sq
> +)
can we replace the double quot with a single quot?

2023-05-09 12:31 UTC, MohamadJaara requested changes
All good, just a small suggestion about using single quot

2023-05-09 13:56 UTC, vitorhugods approved these changes
Nice

2023-05-09 16:04 UTC, MohamadJaara approved these changes

2023-05-10 08:03 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/wireapp/kalium?pullRequest=1698) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/wireapp/kalium?pullRequest=1698) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/wireapp/kalium?pullRequest=1698) it.</sub>

2023-05-10 09:36 UTC, merged