feat(offline-backends): users and conversations without metadata refetch (AR-3123)
wireapp/kalium pull request #1736
Opened 2023-05-15 10:16 UTC by yamilmedina

----
#### PR Submission Checklist for internal contributors

- The **PR Title**
  - [x] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
  - [x] contains a reference JIRA issue number like `SQPIT-764`
  - [x] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
  - [x] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

### Issues

We need to refetch users and conversations without metadata.

### Causes (Optional)

In case we don't have data due to a remote backend being offline, the clients will be able to refetch this data on demand.

### Solutions

This PR adds:

- Persist of failed conversations with defailt values, so we can refetch them later
- Logic and use case to refetch users without metadata on demand.

### Testing

WIP

#### Test Coverage (Optional)

- [ ] I have added automated test to this contribution

### Notes (Optional)

Will raise a new PR to add a new mechanism for refetch every 3 hours if the app comes to foreground.

----
#### PR Post Submission Checklist for internal contributors (Optional)

 - [ ] Wire's Github Workflow has automatically linked the PR to a JIRA issue
----
#### PR Post Merge Checklist for internal contributors

 - [x] If any soft of configuration variable was introduced by this PR, it has been added to the relevant documents and the CI jobs have been updated.
----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

2023-05-16 15:38 UTC, alexandreferris reviewed
Great work! I just have one tiny comment about function naming :)

2023-05-16 15:45 UTC, typfel requested changes

2023-05-16 15:45 UTC, typfel commented on logic/src/commonMain/kotlin/com/wire/kalium/logic/data/conversation/ConversationMapper.kt
> +    override fun fromFailedConversationToEntity(conversationId: NetworkQualifiedId): ConversationEntity = ConversationEntity(
Sorry, missed this PR and only commented on part 2. 

I think we should consider adding field like `hasIncompleteMetadata = true` in this case. This way we don't need to rely on a heuristic like name being null to figure out that conversation needs to be re-fetched.

2023-05-17 16:11 UTC, typfel approved these changes
👍

2023-05-19 09:29 UTC, alexandreferris approved these changes

2023-05-19 09:43 UTC, merged