feat: Added methods to log self deletion info in a structured way [AR-3438]
wireapp/kalium pull request #1748
Opened 2023-05-19 10:10 UTC by gongracr

----
#### PR Submission Checklist for internal contributors

- The **PR Title**
  - [x] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
  - [ ] contains a reference JIRA issue number like `SQPIT-764`
  - [x] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
  - [x] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

### Issues

Added some methods to log info about self deletion objects and team events updating current feature config model.

----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

2023-05-19 11:17 UTC, tmspzz requested changes

2023-05-19 11:17 UTC, tmspzz commented on logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/selfdeletingMessages/SelfDeletionTimer.kt
> +        selfDeletionKey to this::class.simpleName,
not sure this will work with `simpleName`. it will show mangled on release builds. Please use a string instead

2023-05-19 11:17 UTC, tmspzz commented on logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/selfdeletingMessages/PersistNewSelfDeletionTimerUseCase.kt
> +                "Failure while persisting a new Self Deletion Timer for conversation=${conversationId.toLogString()} with " +
This is not structured, the whole event must be represented as json

`Self Deleting Failure: {json-of-the-event-to-log}`

2023-05-19 11:17 UTC, tmspzz commented on logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/selfdeletingMessages/PersistNewSelfDeletionTimerUseCase.kt
> +                "A new Self Deletion Timer for conversation=${conversationId.toLogString()} was successfully updated: " +
Same here

2023-06-05 15:03 UTC, tmspzz approved these changes

2023-06-05 15:19 UTC, trOnk12 approved these changes

2023-06-05 16:10 UTC, merged