fix: clear conversation content can fail
wireapp/kalium pull request #1851
Opened 2023-07-02 22:22 UTC by MohamadJaara

----
#### PR Submission Checklist for internal contributors

- The **PR Title**
  - [ ] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
  - [ ] contains a reference JIRA issue number like `SQPIT-764`
  - [ ] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
  - [ ] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

### Issues

if a conversation is not opening because of a crash in the mappers, then the user is not able to clear the content

### Solutions

refactor the use case and remove it's on reliant on mappers  

Needs releases with:

- [ ] https://github.com/wireapp/kalium/pull/1849

### Testing

#### Test Coverage (Optional)

- [ ] I have added automated test to this contribution

#### How to Test

_Briefly describe how this change was tested and if applicable the exact steps taken to verify that it works as expected._

### Notes (Optional)

_Specify here any other facts that you think are important for this issue._

### Attachments (Optional)

_Attachments like images, videos, etc. (drag and drop in the text box)_

----
#### PR Post Submission Checklist for internal contributors (Optional)

 - [ ] Wire's Github Workflow has automatically linked the PR to a JIRA issue
----
#### PR Post Merge Checklist for internal contributors

 - [ ] If any soft of configuration variable was introduced by this PR, it has been added to the relevant documents and the CI jobs have been updated.
----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

2023-07-03 08:58 UTC, typfel commented
@MohamadJaara update the target branch to the MemberDAO refactoring branch so that we get usable diff of the changes.

2023-07-05 06:16 UTC, typfel requested changes
Looking good, just some nit picks.

2023-07-05 06:16 UTC, typfel commented on logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/UserSessionScope.kt
> +            val convRepo = conversationRepository
Delete, or what purpose this `val` serve?

2023-07-05 06:16 UTC, typfel commented on persistence/src/commonTest/kotlin/com/wire/kalium/persistence/dao/ConversationDAOTest.kt
> -    // Mateusz : This test is failing because of some weird issue, I do not want to block this feature
Why remove this comment? The test is still commented out.

2023-07-05 08:56 UTC, typfel approved these changes

2023-07-07 11:26 UTC, tmspzz approved these changes

2023-07-07 11:38 UTC, merged