fix: set default value of camera for incoming calls (WPB-1712)
wireapp/kalium pull request #1880
Opened 2023-07-13 12:59 UTC by ohassine

----
#### PR Submission Checklist for internal contributors

- The **PR Title**
  - [ ] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
  - [ ] contains a reference JIRA issue number like `SQPIT-764`
  - [ ] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
  - [ ] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

### Issues

in OnIncomingCall callback, the camera default value is set to `isVideoCall` which can lead to this crash 
https://wearezeta.atlassian.net/browse/WPB-1712

### Solutions

The default value of camera should be false by default for incoming calls.

----
#### PR Post Submission Checklist for internal contributors (Optional)

 - [ ] Wire's Github Workflow has automatically linked the PR to a JIRA issue
----
#### PR Post Merge Checklist for internal contributors

 - [ ] If any soft of configuration variable was introduced by this PR, it has been added to the relevant documents and the CI jobs have been updated.
----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

2023-07-13 13:05 UTC, MohamadJaara requested changes

2023-07-13 13:12 UTC, ohassine commented on logic/src/commonJvmAndroid/kotlin/com/wire/kalium/logic/feature/call/scenario/OnIncomingCall.kt
> +                isCameraOn = false,
Can't be removed `override fun onIncomingCall()`, it's callback from AVS

2023-07-14 08:34 UTC, tmspzz approved these changes

2023-07-14 08:35 UTC, tmspzz approved these changes

2023-07-14 08:38 UTC, MohamadJaara approved these changes

2023-07-14 08:57 UTC, merged