feat: Get and save clients mlsPublicKeys (WB-2308)
wireapp/kalium pull request #1932
Opened 2023-08-01 09:13 UTC by borichellow

----
#### PR Submission Checklist for internal contributors

- The **PR Title**
  - [ ] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
  - [ ] contains a reference JIRA issue number like `SQPIT-764`
  - [ ] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
  - [ ] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

### Issues

_Briefly describe the issue you have solved or implemented with this pull request. If the PR contains multiple issues, use a bullet list._

### Causes (Optional)

_Briefly describe the causes behind the issues. This could be helpful to understand the adopted solutions behind some nasty bugs or complex issues._

### Solutions

_Briefly describe the solutions you have implemented for the issues explained above._

### Dependencies (Optional)

_If there are some other pull requests related to this one (e.g. new releases of frameworks), specify them here._

Needs releases with:

- [ ] GitHub link to other pull request

### Testing

#### Test Coverage (Optional)

- [ ] I have added automated test to this contribution

#### How to Test

_Briefly describe how this change was tested and if applicable the exact steps taken to verify that it works as expected._

### Notes (Optional)

_Specify here any other facts that you think are important for this issue._

### Attachments (Optional)

_Attachments like images, videos, etc. (drag and drop in the text box)_

----
#### PR Post Submission Checklist for internal contributors (Optional)

 - [ ] Wire's Github Workflow has automatically linked the PR to a JIRA issue
----
#### PR Post Merge Checklist for internal contributors

 - [ ] If any soft of configuration variable was introduced by this PR, it has been added to the relevant documents and the CI jobs have been updated.
----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

2023-08-01 09:14 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/wireapp/kalium?pullRequest=1932) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/wireapp/kalium?pullRequest=1932) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: MohamadJaara<br/>:x: borichellow<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/wireapp/kalium?pullRequest=1932) it.</sub>

2023-08-02 08:09 UTC, typfel commented on logic/src/commonMain/kotlin/com/wire/kalium/logic/data/client/ClientRepository.kt
> +                    println("cyka ${it.model} ${it.mlsPublicKeys}")
Delete?

```suggestion
```

2023-08-02 08:11 UTC, typfel requested changes
Some minor comments otherwise looks fine but can you also add a description to the PR which explains why we need to save the public keys?

2023-08-02 08:51 UTC, borichellow commented
> Some minor comments otherwise looks fine but can you also add a description to the PR which explains why we need to save the public keys?

it was kinda draft, now everything is fixed :)

2023-08-02 12:13 UTC, typfel approved these changes

2023-08-03 08:14 UTC, alexandreferris approved these changes

2023-08-03 08:20 UTC, mchenani approved these changes
🥳

2023-08-03 08:47 UTC, merged