feat: E2EI renew logic (WPB-3326)
wireapp/kalium pull request #1971
Opened 2023-08-09 09:59 UTC by borichellow

----
#### PR Submission Checklist for internal contributors

- The **PR Title**
  - [ ] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
  - [ ] contains a reference JIRA issue number like `SQPIT-764`
  - [ ] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
  - [ ] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

### Issues

_Briefly describe the issue you have solved or implemented with this pull request. If the PR contains multiple issues, use a bullet list._

### Causes (Optional)

_Briefly describe the causes behind the issues. This could be helpful to understand the adopted solutions behind some nasty bugs or complex issues._

### Solutions

_Briefly describe the solutions you have implemented for the issues explained above._

### Dependencies (Optional)

_If there are some other pull requests related to this one (e.g. new releases of frameworks), specify them here._

Needs releases with:

- [ ] GitHub link to other pull request

### Testing

#### Test Coverage (Optional)

- [ ] I have added automated test to this contribution

#### How to Test

_Briefly describe how this change was tested and if applicable the exact steps taken to verify that it works as expected._

### Notes (Optional)

_Specify here any other facts that you think are important for this issue._

### Attachments (Optional)

_Attachments like images, videos, etc. (drag and drop in the text box)_

----
#### PR Post Submission Checklist for internal contributors (Optional)

 - [ ] Wire's Github Workflow has automatically linked the PR to a JIRA issue
----
#### PR Post Merge Checklist for internal contributors

 - [ ] If any soft of configuration variable was introduced by this PR, it has been added to the relevant documents and the CI jobs have been updated.
----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

2023-08-09 09:59 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/wireapp/kalium?pullRequest=1971) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/wireapp/kalium?pullRequest=1971) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/wireapp/kalium?pullRequest=1971) it.</sub>

2023-08-10 15:03 UTC, vitorhugods requested changes
Looking pretty good to me, just curious about the `time` parameter when marking as notified.

2023-08-11 08:30 UTC, mchenani commented on logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/user/MarkEnablingE2EIAsNotifiedUseCase.kt
> +        userConfigRepository.snoozeE2EINotification(snoozeTime(timeLeft))
The user can snooze the notification and we remind the user in that time frame. But the naming I think can be improved and the documentation needs to be added.

2023-08-11 08:32 UTC, mchenani commented on logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/user/ObserveE2EIRequiredUseCase.kt
> +        .coerceAtLeast(0L)
**Suggestion**: define a variable for this magic number.

2023-08-11 11:32 UTC, mchenani approved these changes

2023-08-11 13:48 UTC, vitorhugods approved these changes

2023-08-14 07:19 UTC, merged