feat: move mls specific endpoints to v5 (WPB-1124)
wireapp/kalium pull request #2011
Opened 2023-08-25 10:22 UTC by yamilmedina

----
#### PR Submission Checklist for internal contributors

- The **PR Title**
  - [x] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
  - [x] contains a reference JIRA issue number like `SQPIT-764`
  - [x] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
  - [x] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

### Issues

This PR is part 2, and contains

- Move MLS related endpoints to v5 development version.

Needs releases with:

- https://github.com/wireapp/kalium/pull/2001

- [x] GitHub link to other pull request

### Testing

#### Test Coverage (Optional)

- [x] I have added automated test to this contribution

----
#### PR Post Submission Checklist for internal contributors (Optional)

 - [ ] Wire's Github Workflow has automatically linked the PR to a JIRA issue
----
#### PR Post Merge Checklist for internal contributors

 - [x] If any soft of configuration variable was introduced by this PR, it has been added to the relevant documents and the CI jobs have been updated.
----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

2023-08-25 12:36 UTC, typfel requested changes
Two things:
- You probably need to move `updateSupportedProtocols` in  `SelfAPIV4` to v5
- in `FeatureSupportImpl` the required api version for `isMLSSupported` needs to be bumped to 5

2023-08-25 16:12 UTC, yamilmedina commented
> Two things:
> 
> * You probably need to move `updateSupportedProtocols` in  `SelfAPIV4` to v5
> * in `FeatureSupportImpl` the required api version for `isMLSSupported` needs to be bumped to 5

Thanks, i moved the `isMLSSupported` version to 5, but the first point, about `SelfAPIV4`, I don't see the implementation on the `release/candidate` 🤔

2023-08-25 20:22 UTC, typfel commented
> > Two things:
> 
> > 
> 
> > * You probably need to move `updateSupportedProtocols` in  `SelfAPIV4` to v5
> 
> > * in `FeatureSupportImpl` the required api version for `isMLSSupported` needs to be bumped to 5
> 
> 
> 
> Thanks, i moved the `isMLSSupported` version to 5, but the first point, about `SelfAPIV4`, I don't see the implementation on the `release/candidate` 🤔 

Ah maybe it's on the mls epic branch. All good then.

2023-08-28 07:55 UTC, typfel approved these changes

2023-08-28 08:18 UTC, mchenani approved these changes

2023-08-28 08:40 UTC, merged