feat: SelfClientsUseCase [AR-980]
wireapp/kalium pull request #204
Opened 2022-02-09 17:37 UTC by MohamadJaara

----
#### PR Submission Checklist for internal contributors

- The **PR Title**
  - [x] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
  - [ ] contains a reference JIRA issue number like `SQPIT-764`
  - [x] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
  - [x] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

### Issues

[AR-980]

### Solutions

implemnting SelfClientsUseCase

Needs releases with:

- [ ] GitHub link to other pull request

### Testing
WIP

----
#### PR Post Merge Checklist for internal contributors

 - [x] If any soft of configuration variable was introduced by this PR, it has been added to the relevant documents and the CI jobs have been updated.
----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

2022-02-10 16:23 UTC, typfel commented on logic/src/commonMain/kotlin/com/wire/kalium/logic/data/client/ClientModel.kt
> +    val clientId: ClientId /* = com.wire.kalium.logic.data.id.PlainId */
Is this common practice? To write a comment everywhere you use a typealias?

2022-02-10 16:27 UTC, typfel requested changes

2022-02-10 16:27 UTC, typfel commented on logic/src/commonMain/kotlin/com/wire/kalium/logic/data/client/remote/ClientRemoteRepository.kt
> +    override suspend fun fetchSelfUserClient(): Either<CoreFailure, List<Client>> {
```suggestion
    override suspend fun fetchSelfUserClients(): Either<CoreFailure, List<Client>> {
```

2022-02-11 12:28 UTC, vitorhugods approved these changes

2022-02-11 12:28 UTC, vitorhugods commented on logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/client/ClientScope.kt
> +    // TODO : get() ?
I guess?

2022-02-11 12:28 UTC, vitorhugods commented on logic/src/commonMain/kotlin/com/wire/kalium/logic/data/client/ClientRepository.kt
> +        clientRegistrationStorage.registeredClientId = clientId.value
This makes me think... we are never catching DB Exceptions.

Maybe in the future we could wrap repositories' operations that touch the DB to catch them and return do something like:

```kotlin
fun wrapDBOperation(action: () -> T): Either<CoreFailure, T> {
    return try {
        Either.Right(action())
    } catch(dbException: SQLException){
        Either.Left(CoreFailure.MrUserIDontFeelSoGood)
    }
}
```

2022-02-11 14:22 UTC, typfel approved these changes

2022-02-11 14:23 UTC, merged