feat: SystemMessage about MLS verified conversation
wireapp/kalium pull request #2104
Opened 2023-09-28 13:39 UTC by borichellow

# What's new in this PR?

When the MLS conversation becomes Verified, app informs user about it by adding SystemMessage

2023-09-28 13:39 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/wireapp/kalium?pullRequest=2104) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/wireapp/kalium?pullRequest=2104) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/wireapp/kalium?pullRequest=2104) it.</sub>

2023-09-28 14:53 UTC, alexandreferris approved these changes

2023-09-29 07:43 UTC, Garzas requested changes
Looking good, but can we have some tests for it? 😄

2023-09-29 08:21 UTC, borichellow commented
> Looking good, but can we have some tests for it? 😄

there is one test updated in `MLSConversationsVerificationStatusesHandlerTest` ;)

2023-09-29 08:27 UTC, Garzas approved these changes

2023-09-29 09:16 UTC, merged