feat: mls add participants for unreachable (WPB-2229)
wireapp/kalium pull request #2275
Opened 2023-11-28 17:15 UTC by yamilmedina

----
#### PR Submission Checklist for internal contributors

- The **PR Title**
  - [x] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
  - [x] contains a reference JIRA issue number like `SQPIT-764`
  - [x] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
  - [x] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

### Issues

No special handling for federated environments for adding participants in an MLS conversation.

### Causes (Optional)

Not implemented.

### Solutions

Handle retry mechanism, when claiming packages fails due to:
- Not available packages
- Unreachable backends and NFCG

Handle retry mechanism, when post commit bundle fails due to:
- Unreachable backends and NFCG

Reusing some of the prev work like `RetryableFailure`, System messages creator to name a few.

Needs releases with:

- [ ] GitHub link to other pull request

### Testing

#### Test Coverage (Optional)

- [ ] I have added automated test to this contribution

#### How to Test

_Briefly describe how this change was tested and if applicable the exact steps taken to verify that it works as expected._

----
#### PR Post Submission Checklist for internal contributors (Optional)

 - [ ] Wire's Github Workflow has automatically linked the PR to a JIRA issue
----
#### PR Post Merge Checklist for internal contributors

 - [ ] If any soft of configuration variable was introduced by this PR, it has been added to the relevant documents and the CI jobs have been updated.
----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

2023-12-01 15:28 UTC, alexandreferris approved these changes
👌🏻

2023-12-04 11:27 UTC, mchenani approved these changes
🦾

2023-12-05 10:32 UTC, typfel requested changes

2023-12-05 14:37 UTC, yamilmedina commented on logic/src/commonMain/kotlin/com/wire/kalium/logic/data/conversation/ConversationGroupRepository.kt
> +                                tryAddMembersToMLSGroup(conversationId, protocol.groupId, userIdList)
Makes sense, change applied

2023-12-06 12:06 UTC, typfel approved these changes

2023-12-06 12:29 UTC, merged