rerelease of infinitemonkeys helm chart
wireapp/kalium pull request #2610
Opened 2024-03-11 11:11 UTC by jschumacher-wire

WPB-2595 / WPB-6448

* adding readme
* minor refactor
* removing nested docker install from Dockerfile

This PR adds a helm chart for Infinite Monkeys, enabling native K8s deployments with any number of test users (eg. monkeyServer pods).

2024-03-11 11:36 UTC, augustocdias approved these changes

2024-03-11 12:12 UTC, mastaab requested changes

2024-03-11 12:12 UTC, mastaab commented on monkeys/helm/infinitemonkeys/Chart.yaml
> +dependencies:
please remove the dependency

2024-03-11 12:12 UTC, mastaab commented on monkeys/helm/infinitemonkeys/Readme.md
> +- Integration with Prometheus and Grafana via dependency "kube-prometheus-stack"
- Integration with Prometheus-Operator via PodMonitors and a Grafana Dashboard

2024-03-11 12:12 UTC, mastaab commented on monkeys/helm/infinitemonkeys/templates/configmaps.yaml
> +apiVersion: v1
Please introduce a values parameter, that enables or disables the monitoring integration - subsequently then creates the dashboard and podmonitors if set to "true"

2024-03-11 12:12 UTC, mastaab commented on monkeys/helm/infinitemonkeys/templates/podmonitor.yaml
> +spec:
please add the standard helm labels
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"

2024-03-11 12:12 UTC, mastaab commented on monkeys/helm/infinitemonkeys/templates/podmonitor.yaml
> +spec:
also here

2024-03-11 12:12 UTC, mastaab commented on monkeys/helm/infinitemonkeys/values.yaml
> +monkeyServer:
maybe this can be calculated with userCount +1 ?
so we don't need an additional parameter

2024-03-11 19:52 UTC, mastaab approved these changes

2024-03-15 12:30 UTC, mastaab approved these changes

2024-03-15 12:30 UTC, mastaab commented on monkeys/helm/infinitemonkeys/templates/monkey-controller.yaml
> +            - '-d1500'
they serve different purposes
the -d is to delay the time for a new conversation to be added to the pool for other monkeys to use
this is to reduce the conversation not found errors

2024-03-18 10:21 UTC, merged