Feat: AR-952 login after register
wireapp/kalium pull request #265
Opened 2022-03-10 14:20 UTC by MohamadJaara

----
#### PR Submission Checklist for internal contributors

- The **PR Title**
  - [ ] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
  - [ ] contains a reference JIRA issue number like `SQPIT-764`
  - [ ] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
  - [ ] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

### Issues

AR-952

### Solutions

call login after register

Needs releases with:

- [ ] GitHub link to other pull request

### Testing
uint test

----
#### PR Post Submission Checklist for internal contributors (Optional)

 - [ ] Wire's Github Workflow has automatically linked the PR to a JIRA issue
----
#### PR Post Merge Checklist for internal contributors

 - [ ] If any soft of configuration variable was introduced by this PR, it has been added to the relevant documents and the CI jobs have been updated.
----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

2022-03-15 09:07 UTC, mchenani commented on logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/register/RegisterAccountUseCase.kt
> +sealed class RegistrationParam(
All the registration related classes have Register* naming pattern, do you think it's better to apply that name pattern here? `RegisterParam` or rename other to this pattern `RegistrationResult`.

2022-03-15 09:25 UTC, mchenani commented on logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/register/RequestActivationCodeUseCase.kt
> +}
```suggestion
    suspend operator fun invoke(email: String, serverConfig: ServerConfig) = registerAccountRepository.
   requestEmailActivationCode(email, serverConfig.apiBaseUrl)
        .fold({
            RequestActivationCodeResult.Failure.Generic(it)
        }, {
            RequestActivationCodeResult.Success
        })
}
```

what do you think of ignoring body definition for function with one return?

2022-03-15 09:27 UTC, mchenani commented on logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/register/VerifyActivationCodeUseCase.kt
> +        return registerAccountRepository.verifyActivationCode(email, code, serverConfig.apiBaseUrl)
The same body definition applied here. Just in case if you agree with me then we need to change this.

2022-03-15 09:31 UTC, mchenani requested changes
Well done buddy! few tiny suggestions🥁

2022-03-16 11:36 UTC, typfel approved these changes
LGTM but I'm also not that knowledgable about the network module.

2022-03-16 16:11 UTC, mchenani commented on network/src/commonMain/kotlin/com/wire/kalium/network/api/user/logout/LogoutApi.kt
> +        }
I think the name of `removeCookiesByIdsRequest` should be `removeCookiesByLabelsRequest`, am I right? 
```suggestion
    override suspend fun removeCookiesByLabels(removeCookiesByLabelsRequest: RemoveCookiesByLabels): NetworkResponse<Unit> =
        wrapKaliumResponse {
            httpClient.post("$PATH_COOKIES/$PATH_REMOVE") {
                setBody(removeCookiesByLabelsRequest)
            }
        }
```

2022-03-16 16:15 UTC, mchenani approved these changes
Great PR, well done!🔥 + One small renaming issue!

2022-03-16 17:02 UTC, merged