fix: UseCase for getting if one on one conversation with user exist [WPB-6936]
wireapp/kalium pull request #2713
Opened 2024-04-23 09:37 UTC by borichellow

# What's new in this PR?

Added `IsOneToOneConversationCreatedUseCase` for getting if 1o1 conversation with user exists

2024-04-23 11:08 UTC, MohamadJaara requested changes

2024-04-23 11:08 UTC, MohamadJaara commented on logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/conversation/IsOneToOneConversationCreatedUseCase.kt
> +    }
this query is selecting from the `ConversationDetails` view with quite some joins, if the goal is only to check if there is an established 1:1 then you can 

```sql 
SELECT active_one_on_one_conversation_id 
FROM User 
WHERE qualified_id = 'your_user_id';
```
and a simple chck if this returns a null or not should do the trick

2024-04-25 12:49 UTC, vitorhugods approved these changes

2024-04-25 13:38 UTC, MohamadJaara approved these changes

2024-04-25 15:53 UTC, merged