fix: repositoriesShouldNotAccessFeature in MLSConversationRepository [WPB-6326]
wireapp/kalium pull request #2736
Opened 2024-05-02 14:19 UTC by borichellow

# What's new in this PR?

### Issues

MLSConversationRepository was accessing the useCase from Feature module

### Causes (Optional)

It was done like that

### Solutions

Move `CheckRevocationListUseCase` into Logic module and update it to not use UseCases from the Feature. 
This UseCase is used only in kalium, so it doesn't affect Android part.

2024-05-02 16:16 UTC, yamilmedina approved these changes

2024-05-03 04:57 UTC, mchenani approved these changes

2024-05-03 10:07 UTC, vitorhugods requested changes
Nice to dedicate some time to fix this.

But I think just moving the file and adding "internal" to the name isn't enough.

This is just moving a `"UseCase"` to `data`, which is not a pattern we should follow.

Unlike real use cases, this one is not public, it shouldn't be used by the apps.

It's an internal, reusable piece of logic that other use cases (and even repositories) are using. So removing this suffix would be better.

2024-05-06 09:06 UTC, vitorhugods approved these changes

2024-05-06 10:34 UTC, merged