refactor: refactor CoreFailure part-2 (storage)
wireapp/kalium pull request #275
Opened 2022-03-15 09:39 UTC by MohamadJaara

----
#### PR Submission Checklist for internal contributors

- The **PR Title**
  - [x] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
  - [ ] contains a reference JIRA issue number like `SQPIT-764`
  - [x] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
  - [x] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

###Issues

the way API, DB, and Crypto errors are handled in logic is a bit chaotic which lead to different implementation of error handling by repositories

###Solutions

there will be a series of PRs to unify error Handling
changes in this PR:
1 - wrapStorageRequest to catch any DB/preferences errors
2 - handling errors in AssetRepository.kt, ClientRepository.kt and ConversationRepository.kt (to avoid big PR)

Needs releases with:

- [ ] GitHub link to other pull request

### Testing

WIP

----
#### PR Post Submission Checklist for internal contributors (Optional)

 - [ ] Wire's Github Workflow has automatically linked the PR to a JIRA issue
----
#### PR Post Merge Checklist for internal contributors

 - [ ] If any soft of configuration variable was introduced by this PR, it has been added to the relevant documents and the CI jobs have been updated.
----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

2022-03-15 17:54 UTC, vitorhugods requested changes
Very tiny suggestions.

Nice to have the DB operations taken care of. Great work!

Just in order to keep it tidier in the future, I would suggest doing renaming of the Entity classes in a different PR from this. Especially because the failure handling is quite crucial and could be already merged, but renaming/refactoring is prone to a lot of merge conflicts that can hold the PR down.

2022-03-15 17:54 UTC, vitorhugods commented on persistence/src/commonMain/kotlin/com/wire/kalium/persistence/dao/ConversationDAO.kt
> +// TODO: add conversation / user table
Doesn't the `Member` table already serve this purpose?

2022-03-21 22:42 UTC, MohamadJaara commented on logic/src/commonMain/kotlin/com/wire/kalium/logic/data/conversation/MemberMapper.kt
> +import com.wire.kalium.persistence.dao.MemberEntity as PersistedMember
I did revert the Class naming change because of conflicts

2022-03-23 15:44 UTC, MohamadJaara commented
This PR for  is ready to review, there is an issue that I am aware of, which is using 
`wrapStorageRequest` on functions that could return null, I will address it in a later PR

2022-03-25 14:35 UTC, gongracr commented on android/src/main/kotlin/com/wire/kalium/presentation/MainActivity.kt
> +                        throw IllegalStateException(result.storageFailure.rootCause)
Not important at all, but wouldn't an `IOException` suit better?

2022-03-25 14:35 UTC, gongracr commented on logic/src/commonMain/kotlin/com/wire/kalium/logic/CoreFailure.kt
> +        Either.Left(NetworkFailure.ServerMiscommunication(e))
No more crashes due to weird backend responses! 👏

2022-03-25 14:35 UTC, gongracr commented on logic/src/commonMain/kotlin/com/wire/kalium/logic/data/asset/AssetRepository.kt
>          val persistedAsset = assetDao.getAssetByKey(assetKey).firstOrNull()
Why aren't we enclosing this also with `wrapStorageRequest { ... }`?

2022-03-29 11:27 UTC, gongracr approved these changes
LGTM, great to see DB exceptions also being handled 🎰 🥇

2022-03-30 15:01 UTC, vitorhugods approved these changes

2022-03-30 17:11 UTC, merged