fix(mls-migration): allow skipping users without KeyPackages during MLS migration (WPB-9638)
wireapp/kalium pull request #2845
Opened 2024-06-26 14:24 UTC by mchenani

…ls migration

----
#### PR Submission Checklist for internal contributors

- The **PR Title**
  - [x] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
  - [x] contains a reference JIRA issue number like `SQPIT-764`
  - [x] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
  - [ ] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?
When the migration started by android, and it needs to be finalised, we must migrate the groups even if there are users don't have keypackages or mls clients!
In this PR during the migration we set establish mls group with allowing partial member adding enabled.

### Notes (Optional)

_Specify here any other facts that you think are important for this issue._

### Attachments (Optional)

_Attachments like images, videos, etc. (drag and drop in the text box)_

----
#### PR Post Submission Checklist for internal contributors (Optional)

 - [ ] Wire's Github Workflow has automatically linked the PR to a JIRA issue
----
#### PR Post Merge Checklist for internal contributors

 - [ ] If any soft of configuration variable was introduced by this PR, it has been added to the relevant documents and the CI jobs have been updated.
----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

2024-06-26 16:22 UTC, Garzas requested changes
Looking good, just comments about logger 🥇

2024-06-26 16:22 UTC, Garzas commented on logic/src/commonMain/kotlin/com/wire/kalium/logic/data/conversation/MLSConversationRepository.kt
> +            kaliumLogger.w("adding ${userIdList.count()} users to MLS group")
I think it's not a warning 😄

2024-06-26 16:22 UTC, Garzas commented on logic/src/commonMain/kotlin/com/wire/kalium/logic/data/conversation/MLSConversationRepository.kt
> +                        kaliumLogger.w("add members to MLS Group: claiming KeyPackages succeed")
Same here

2024-07-01 08:14 UTC, Garzas approved these changes

2024-07-01 08:15 UTC, alexandreferris approved these changes

2024-07-01 08:18 UTC, merged