perf: improve ProteusClientCoreCrypto performance [WPB-10000]
wireapp/kalium pull request #2974
Opened 2024-08-28 12:21 UTC by vitorhugods

----
#### PR Submission Checklist for internal contributors

- The **PR Title**
  - [X] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
  - [X] contains a reference JIRA issue number like `SQPIT-764`
  - [X] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
  - [X] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

### Issues

We're a bit slow to process events. 

### Causes

In part, it's nature of E2EE. In part, we are not really being optimal.

In the generic sense, we can improve Proteus/CoreCrypto performance by not saving session (which is unnecessary, as CoreCrypto already does it during decryption), and also avoid checking if the session exists over and over again if we already know it exists.

### Solutions

1. Remove the "saveSession" bit of `ProteusClientCoreCrypto`.
2. Cache known sessions in-memory and check that instead of relying only on CoreCrypto, which uses IO in order to do that

----
#### PR Post Merge Checklist for internal contributors

 - [X] If any soft of configuration variable was introduced by this PR, it has been added to the relevant documents and the CI jobs have been updated.
----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

2024-08-28 12:34 UTC, alexandreferris approved these changes

2024-08-28 16:02 UTC, MohamadJaara approved these changes
this change is a nice candidate for a ADR, just saying it does not need to be the whole notebook, but maybe small description with a link to the notebook

2024-08-29 07:17 UTC, yamilmedina requested changes
Great work and nice introduction of these `notebooks`
Just left one suggestion/question about naming and breaking patterns. 

Also agree with Mo, this is a good candidate for an ADR, maybe for a next PR 🤔

2024-08-29 07:17 UTC, yamilmedina commented on Notebooks/README.md
> +A place to store [Jupyter Notebook](https://jupyter.org/) files of ongoing studies.
Suggestion/question: Can we maintain the patterns here for naming folders ? 😬 
Meaning, Is there a reason why is this different from the rest ? Didn't find anything on the docs

2024-09-02 08:09 UTC, vitorhugods commented
> Great work and nice introduction of these `notebooks` Just left one suggestion/question about naming and breaking patterns.
> 
> Also agree with Mo, this is a good candidate for an ADR, maybe for a next PR 🤔

About ADRs... do we have ADRs on Kalium as well? Because this was the main reason that made me not do it. I am starting to think we should merge the repos more and more.

----

I just did `Notebooks` instead of `notebooks` because it is indeed different from the rest. Maybe `docs` would be better. I'll rename it to something like that.

2024-09-02 08:35 UTC, yamilmedina approved these changes

2024-09-02 10:37 UTC, merged