feat: network observer cover from not connected and blocked to connected (WPB-11200)
wireapp/kalium pull request #3057
Opened 2024-10-11 17:50 UTC by yamilmedina

----
#### PR Submission Checklist for internal contributors

- The **PR Title**
  - [x] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
  - [x] contains a reference JIRA issue number like `SQPIT-764`
  - [x] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
  - [x] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

### Issues

There is one case that seems to be not covered by the network state observer being:

`Not connected -> to Unblocked = Connected`

### Causes (Optional)

Potentially hanging the state until a new connected state is triggered.

### Solutions

Covering all grounds by adding this case and some logs to help debugging in datadog

### Testing

#### Test Coverage (Optional)

- [x] I have added automated test to this contribution

### Notes (Optional)

For now I'm testing this in an local build, to gather logs and monitor improvements

----
#### PR Post Submission Checklist for internal contributors (Optional)

 - [x] Wire's Github Workflow has automatically linked the PR to a JIRA issue
----
#### PR Post Merge Checklist for internal contributors

 - [x] If any soft of configuration variable was introduced by this PR, it has been added to the relevant documents and the CI jobs have been updated.
----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

2024-10-14 08:26 UTC, Garzas approved these changes

2024-10-14 08:48 UTC, damian-kaczmarek requested changes
I was able to produce this strange state where there is no connection but app do not register that. @yamilmedina Do you think this is a part of this problem or separate issue?

How to reproduce:
- airplane mode on
- wait a little bit
- airplane mode off
- quickly airplane mode on

https://github.com/user-attachments/assets/228bd2eb-cde8-4ce4-8333-d85f0c1ed4aa

2024-10-14 09:49 UTC, yamilmedina commented
> I was able to produce this strange state where there is no connection but app do not register that. @yamilmedina Do you think this is a part of this problem or separate issue?
> 
> How to reproduce:
> 
> * airplane mode on
> * wait a little bit
> * airplane mode off
> * quickly airplane mode on
> 
>  strange_network.mp4

Thanks for the repro info, indeed this case we are trying to cover from many sides, so it is somewhat related.
I will take a look and see if I can include the fix on this PR or maybe create a new ticket if there is more work to do, since this spike would be an option too :D

2024-10-14 16:05 UTC, yamilmedina commented
> I was able to produce this strange state where there is no connection but app do not register that. @yamilmedina Do you think this is a part of this problem or separate issue?
> 
> How to reproduce:
> 
> * airplane mode on
> * wait a little bit
> * airplane mode off
> * quickly airplane mode on
> 
>  strange_network.mp4

I was playing here with some changes, and seems to solve it for me at least. @damian-kaczmarek  Can you try it on your side please to double check :D ?

2024-10-14 17:18 UTC, yamilmedina commented
> I was able to produce this strange state where there is no connection but app do not register that. @yamilmedina Do you think this is a part of this problem or separate issue?
> 
> How to reproduce:
> 
> * airplane mode on
> * wait a little bit
> * airplane mode off
> * quickly airplane mode on
> 
>  strange_network.mp4

Ok, I investigated further, and the issue can happen after the second time in airplane mode (it does no matter if it's quick or not, at least for me). In the worst case, this gets short-circuited after ~20 seconds, when the websocket does a ping, this happens since we delay when no connection for the incremental sync to happen.

I will create a ticket, to see how we can improve this state change, for the scope of this ticket at least is not relevant, since is related to the other case (from no network to connected) and blocking the sync because of it.

2024-10-15 07:10 UTC, damian-kaczmarek reviewed
@yamilmedina I was still able to reproduce it, do we want separate issue for that?

2024-10-15 07:12 UTC, damian-kaczmarek approved these changes

2024-10-15 08:47 UTC, yamilmedina commented
Created a ticket for this other issue here: 
https://wearezeta.atlassian.net/browse/WPB-11568

2024-10-15 09:12 UTC, merged