feat: Consider team settings when registering mls device #WPB-10119
wireapp/kalium pull request #3079
Opened 2024-10-28 07:02 UTC by m-zagorski

https://wearezeta.atlassian.net/browse/WPB-10119

# What's new in this PR?

### Issues

We now need to check team settings before registering a mls client

### Solutions

Add another check before mls device registration

### Testing

#### How to Test

Make sure registering device only when: feature flag is on, mls keys are present and team settings is enabled

----
#### PR Post Submission Checklist for internal contributors (Optional)

 - [ ] Wire's Github Workflow has automatically linked the PR to a JIRA issue
----
#### PR Post Merge Checklist for internal contributors

 - [ ] If any soft of configuration variable was introduced by this PR, it has been added to the relevant documents and the CI jobs have been updated.
----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

2024-10-28 07:14 UTC, MohamadJaara commented on logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/client/IsAllowedToRegisterMLSClientUseCase.kt
>  }
please add tests

2024-10-29 09:27 UTC, Garzas approved these changes

2024-10-30 09:04 UTC, MohamadJaara commented
just synced with Marco and we also eed to remove the compile time flag `KaliumConfig.isMLSSupportEnabled`

2024-10-30 09:49 UTC, m-zagorski commented
> just synced with Marco and we also eed to remove the compile time flag `KaliumConfig.isMLSSupportEnabled` @m-zagorski

Could you check out now ? @MohamadJaara

2024-10-30 10:07 UTC, MohamadJaara requested changes
one final change

2024-10-30 10:07 UTC, MohamadJaara commented on logic/src/commonMain/kotlin/com/wire/kalium/logic/featureFlags/FeatureSupportImpl.kt
> +    override val isMLSSupported: Boolean = apiVersion >= 5
also this line should be api >=6

2024-10-30 10:58 UTC, MohamadJaara approved these changes
LGTM

2024-10-30 11:24 UTC, merged