feature: adopt v7 API #WPB-11975 - adding tests rests can be checked
wireapp/kalium pull request #3099
Opened 2024-11-12 08:53 UTC by damian-kaczmarek

----
#### PR Submission Checklist for internal contributors

- The **PR Title**
  - [ ] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
  - [ ] contains a reference JIRA issue number like `SQPIT-764`
  - [ ] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
  - [ ] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

### Issues

New API version added on backend https://wearezeta.atlassian.net/wiki/spaces/ENGINEERIN/pages/1309868033/API+changes+v6+v7

> [!IMPORTANT]  
> Please verify this list, as part of the CR.

Changes listed in doc (applied ✅ , not relevant ❌ )
- The capabilities field of the Client structure now contains a list of capabilities, rather than a nested object. In the notifications containing the Client structure, it will still be a nested object. ✅
- The notification contains the old format {capabilities: { capabilities: [...] }}, but clients must allow both old and new format starting from V6.  Once V5 is discontinued, the backend will start sending notifications in the new form.✅

- There is a new type of capability in capabilities field for Client: consumable-notifications. This will only show up when using API v7. In the notifications containing the Client structure, this capability will not be visible. ❌

- DELETE /oauth/applications/:id/ is removed in v7 in favor of a new endpoint DELETE /oauth/applications/:id/sessions which takes a request body with an optional password. The password is verified in case of the user is not an SSO user.❌

- renamed POST /users/handles → POST /handles❌

- renamed POST /users/handles → POST /handles❌

- renamed HEAD /users/handles → HEAD /handles❌

- renamed POST /conversations/bots → POST /bot/conversations❌

- renamed DELETE /conversations/bots → DELETE /bot/conversations❌

- renamed POST /conversations/one2one → POST /one2one-conversations ✅

- renamed GET /conversations/one2one → GET /one2one-conversations ✅

- GET /scim/auth-tokens returns an array of ScimTokenInfoitems which now have an additional field: name.❌

- POST /scim/auth-tokens response has a new optional field: name. If not specified, the name will be set to the ID of the SCIM token by the backend.❌

- GET /teams/invitations/info response has a new optional field created_by_email which will be occupied with the inviter’s email in case the invitee is a personal user.❌

### Testing

#### Test Coverage (Optional)

- [ ] I have added automated test to this contribution

#### How to Test

_Briefly describe how this change was tested and if applicable the exact steps taken to verify that it works as expected._

### Notes (Optional)

_Specify here any other facts that you think are important for this issue._

### Attachments (Optional)

_Attachments like images, videos, etc. (drag and drop in the text box)_

----
#### PR Post Submission Checklist for internal contributors (Optional)

 - [ ] Wire's Github Workflow has automatically linked the PR to a JIRA issue
----
#### PR Post Merge Checklist for internal contributors

 - [ ] If any soft of configuration variable was introduced by this PR, it has been added to the relevant documents and the CI jobs have been updated.
----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

2024-11-12 09:03 UTC, MohamadJaara requested changes
suggestion to remove not used modifiers from generated api classes and missing test for the `CapabilitiesDeserializer`

2024-11-12 09:03 UTC, MohamadJaara commented on network/src/commonMain/kotlin/com/wire/kalium/network/api/v7/authenticated/E2EIApiV7.kt
> +    private val authenticatedNetworkClient: AuthenticatedNetworkClient
```suggestion
    authenticatedNetworkClient: AuthenticatedNetworkClient
```

2024-11-12 09:03 UTC, MohamadJaara commented on network/src/commonMain/kotlin/com/wire/kalium/network/api/v7/authenticated/KeyPackageApiV7.kt
> +    private val authenticatedNetworkClient: AuthenticatedNetworkClient
```suggestion
    authenticatedNetworkClient: AuthenticatedNetworkClient
```

2024-11-12 09:03 UTC, MohamadJaara commented on network/src/commonMain/kotlin/com/wire/kalium/network/api/v7/authenticated/MLSMessageApiV7.kt
> +    private val authenticatedNetworkClient: AuthenticatedNetworkClient
```suggestion
    authenticatedNetworkClient: AuthenticatedNetworkClient
```

2024-11-12 09:03 UTC, MohamadJaara commented on network/src/commonMain/kotlin/com/wire/kalium/network/api/v7/authenticated/MLSPublicKeyApiV7.kt
> +    private val authenticatedNetworkClient: AuthenticatedNetworkClient
```suggestion
    authenticatedNetworkClient: AuthenticatedNetworkClient
```

2024-11-12 09:03 UTC, MohamadJaara commented on network/src/commonMain/kotlin/com/wire/kalium/network/api/v7/authenticated/NotificationApiV7.kt
> +    private val authenticatedNetworkClient: AuthenticatedNetworkClient,
```suggestion
    authenticatedNetworkClient: AuthenticatedNetworkClient,
```

2024-11-12 09:03 UTC, MohamadJaara commented on network-model/src/commonMain/kotlin/com/wire/kalium/network/api/authenticated/client/ClientDTO.kt
> +
Can you please add a couple of tests for this serializer

2024-11-18 16:08 UTC, MohamadJaara approved these changes

2024-11-18 16:51 UTC, ohassine approved these changes

2024-11-18 17:47 UTC, merged