Feat/recently ended call metadata
wireapp/kalium pull request #3112
Opened 2024-11-20 08:05 UTC by m-zagorski

https://wearezeta.atlassian.net/browse/WPB-14256

# What's new in this PR?

### Issues

We need to add `Call ended` segementation

### Causes (Optional)

We need raw end call cause and a lot of data. In this PR we're storing recently ended call and give an use case
to create the metadata. I've also have the `compact` version of it (I will link it shortly) that is creating the metadata right away.

### Solutions

Pick up all the things we need, prepare metadata and allow clients to observe them to use them in the analytics

----
#### PR Post Submission Checklist for internal contributors (Optional)

 - [ ] Wire's Github Workflow has automatically linked the PR to a JIRA issue
----
#### PR Post Merge Checklist for internal contributors

 - [ ] If any soft of configuration variable was introduced by this PR, it has been added to the relevant documents and the CI jobs have been updated.
----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

2024-11-20 08:06 UTC, m-zagorski commented on logic/src/commonMain/kotlin/com/wire/kalium/logic/data/call/CallRepository.kt
> +        _recentlyEndedCallFlow.tryEmit(
please also check https://github.com/wireapp/kalium/pull/3113 as this changes this solution to a more compact which does not expose that much

2024-11-20 09:24 UTC, Garzas approved these changes

2024-11-26 11:30 UTC, MohamadJaara requested changes

2024-12-06 13:27 UTC, MohamadJaara requested changes
please merge in 4.11

2024-12-11 15:06 UTC, borichellow approved these changes
looks good to me :)

2024-12-17 09:23 UTC, MohamadJaara approved these changes

2024-12-17 09:59 UTC, merged