feat: add use case to check if backend supports personal to team migration (WPB-12022)
wireapp/kalium pull request #3114
Opened 2024-11-20 10:57 UTC by ohassine

----
#### PR Submission Checklist for internal contributors

- The **PR Title**
  - [ ] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
  - [ ] contains a reference JIRA issue number like `SQPIT-764`
  - [ ] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
  - [ ] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

### Issues

Use case to check if backend supports personal to team account migration

Needs releases with:

- [ ] GitHub link to other pull request

### Testing

#### Test Coverage (Optional)

- [ ] I have added automated test to this contribution

#### How to Test

_Briefly describe how this change was tested and if applicable the exact steps taken to verify that it works as expected._

### Notes (Optional)

_Specify here any other facts that you think are important for this issue._

### Attachments (Optional)

_Attachments like images, videos, etc. (drag and drop in the text box)_

----
#### PR Post Submission Checklist for internal contributors (Optional)

 - [ ] Wire's Github Workflow has automatically linked the PR to a JIRA issue
----
#### PR Post Merge Checklist for internal contributors

 - [ ] If any soft of configuration variable was introduced by this PR, it has been added to the relevant documents and the CI jobs have been updated.
----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

2024-11-20 12:49 UTC, yamilmedina approved these changes

2024-11-20 20:20 UTC, MohamadJaara submitted a review, later dismissed
this is not 100% guarantied to be correct at run time, there is a small chance that an API version is updated after the user session is created therefore the update will not take place until the next app restart

to be 100% accurate you can get the server config from `SessionManager.serverConfig()`

2024-11-21 13:40 UTC, MohamadJaara requested changes

2024-11-21 13:40 UTC, MohamadJaara commented on logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/personaltoteamaccount/CanMigrateFromPersonalToTeamUseCase.kt
> +        return userRepository.getSelfUser()?.teamId == null && commonApiVersion >= minApi
also here this value can be obtained from the selfTeamIdProvider cache

2024-11-22 09:06 UTC, merged