chore: Remove self user creator [WPB-11559]
wireapp/kalium pull request #3118
Opened 2024-11-21 08:17 UTC by m-zagorski

https://wearezeta.atlassian.net/browse/WPB-11559

# What's new in this PR?

### Issues

We dont need the selfUserCreator anymore as the constraints on deleting group have changes, and now we need to belong to the same team.

# Merge after

Merge only after this is merged https://github.com/wireapp/wire-android/pull/3652

----
#### PR Post Submission Checklist for internal contributors (Optional)

 - [ ] Wire's Github Workflow has automatically linked the PR to a JIRA issue
----
#### PR Post Merge Checklist for internal contributors

 - [ ] If any soft of configuration variable was introduced by this PR, it has been added to the relevant documents and the CI jobs have been updated.
----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

2024-11-21 13:39 UTC, MohamadJaara requested changes
please also remove it from the view where it is created

2024-11-22 06:40 UTC, m-zagorski commented
> please also remove it from the view where it is created

should I also remove it from db?

2024-11-22 14:28 UTC, MohamadJaara commented
> > please also remove it from the view where it is created
> 
> should I also remove it from db?

if it is not used anywhere else then yes

2024-11-28 11:37 UTC, MohamadJaara approved these changes

2024-12-02 08:31 UTC, saleniuk approved these changes

2024-12-02 09:05 UTC, merged