feat: harden ClientCapabilityDTO for api v7
wireapp/kalium pull request #3151
Opened 2024-12-06 16:37 UTC by MohamadJaara

----
#### PR Submission Checklist for internal contributors

- The **PR Title**
  - [ ] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
  - [ ] contains a reference JIRA issue number like `SQPIT-764`
  - [ ] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
  - [ ] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

### Issues

make the ClientCapability accept any unknown values

### Causes (Optional)

in the migration from 1pi 6 to 7 there may be a new values there
### Solutions
harden the serilizer to accept unknown values
### Dependencies (Optional)

_If there are some other pull requests related to this one (e.g. new releases of frameworks), specify them here._

Needs releases with:

- [ ] GitHub link to other pull request

### Testing

#### Test Coverage (Optional)

- [ ] I have added automated test to this contribution

#### How to Test

_Briefly describe how this change was tested and if applicable the exact steps taken to verify that it works as expected._

### Notes (Optional)

_Specify here any other facts that you think are important for this issue._

### Attachments (Optional)

_Attachments like images, videos, etc. (drag and drop in the text box)_

----
#### PR Post Submission Checklist for internal contributors (Optional)

 - [ ] Wire's Github Workflow has automatically linked the PR to a JIRA issue
----
#### PR Post Merge Checklist for internal contributors

 - [ ] If any soft of configuration variable was introduced by this PR, it has been added to the relevant documents and the CI jobs have been updated.
----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

2024-12-06 16:38 UTC, yamilmedina approved these changes

2024-12-06 16:52 UTC, vitorhugods approved these changes
Would be nice to write a test for this serialiser.

2024-12-12 15:02 UTC, yamilmedina requested changes
The tests are failing, and sounds a good idea to have for v8.
The code freeze v7 is more clear now and new types will show up only in v8+

Then we can do the usual new API response support we do. @vitorhugods @MohamadJaara  what do you think?

Created a PR in the meantime, with tests for retro compat endpoint. 
https://github.com/wireapp/kalium/pull/3173

2025-01-07 12:09 UTC, MohamadJaara commented
@yamilmedina @vitorhugods i fixed the tests the issue was in how  the row json string are generated

2025-01-07 12:26 UTC, yamilmedina approved these changes

2025-01-09 11:43 UTC, merged