feat: Handle needToRemoveLocally flag [WPB-14603]
wireapp/kalium pull request #3158
Opened 2024-12-10 05:39 UTC by m-zagorski

https://wearezeta.atlassian.net/browse/WPB-14603

# What's new in this PR?

### Issues

Handle `needToRemoveLocally` flag for `Cleared` messages

### Solutions

In this PR we only define it and handle its behavior, we do NOT send it or handle sending right now

----
#### PR Post Submission Checklist for internal contributors (Optional)

 - [ ] Wire's Github Workflow has automatically linked the PR to a JIRA issue
----
#### PR Post Merge Checklist for internal contributors

 - [ ] If any soft of configuration variable was introduced by this PR, it has been added to the relevant documents and the CI jobs have been updated.
----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

2024-12-11 09:24 UTC, vitorhugods requested changes
Well-done, just one small suggestion to rename a variable that doesn't reflect its value/usage properly.

2024-12-11 09:24 UTC, vitorhugods commented on logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/receiver/handler/ClearConversationContentHandler.kt
> +        val isMessageComingFromOtherClient = message.senderUserId != selfUserId
```suggestion
        val isMessageComingFromAnotherUser = message.senderUserId != selfUserId
```

2024-12-13 08:29 UTC, m-zagorski commented on logic/src/commonMain/kotlin/com/wire/kalium/logic/sync/receiver/handler/ClearConversationContentHandler.kt
> +        val isMessageComingFromOtherClient = message.senderUserId != selfUserId
Changed 👍

2024-12-13 13:56 UTC, yamilmedina approved these changes

2024-12-16 12:22 UTC, saleniuk approved these changes

2024-12-16 13:50 UTC, merged