chore: util module and dispatchers
wireapp/kalium pull request #358
Opened 2022-04-05 08:53 UTC by MohamadJaara

----
#### PR Submission Checklist for internal contributors

- The **PR Title**
  - [x] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
  - [ ] contains a reference JIRA issue number like `SQPIT-764`
  - [x] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
  - [x] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

### Issues

kalium missing a shared utility module

### Solutions

add shared util module

----
#### PR Post Merge Checklist for internal contributors

 - [ ] If any soft of configuration variable was introduced by this PR, it has been added to the relevant documents and the CI jobs have been updated.
----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

2022-04-05 16:01 UTC, vitorhugods requested changes

2022-04-05 17:18 UTC, MohamadJaara commented on util/src/commonMain/kotlin/com.wire.kalium.util/KaliumDispatcher.kt
> +}
```kotlin
object KaliumDispatcher {
     val default: CoroutineDispatcher
     val main: MainCoroutineDispatcher
     val unconfined: CoroutineDispatcher
     val io: CoroutineDispatcher
}

expect object KaliumDispatcherImpl: KaliumDispatcher

// usage 
class Foo(private val dispatcher: KaliumDispatcher = KaliumDispatcherImpl) 
``` 
This way we can inject a different Impl for testing

2022-04-06 06:42 UTC, vitorhugods commented on util/src/commonMain/kotlin/com.wire.kalium.util/KaliumDispatcher.kt
> +}
I'm fine with that. :)

2022-04-06 19:20 UTC, vitorhugods approved these changes

2022-04-06 20:36 UTC, merged