fix: Update Firebase token when new comes (AR-2489)
wireapp/kalium pull request #943
Opened 2022-09-21 12:02 UTC by borichellow

# What's new in this PR?

new flow for registering Firebase token 

### Issues

Firebase token is not updated on our BE side if Firebase decides to create a new one (it's rare but possible case).

### Causes (Optional)

FB token when it comes was just saving into local DB and when user login we register that token for the user.

### Solutions

Add some flag into UserScope "shouldUpdateFirebaseToken"
On every `init` in `UserScope` check this `shouldUpdateFirebaseToken` flag if it's true - update the token for BE.
And everytime Firebase generate a new token we save it into local DB **and** set `shouldUpdateFirebaseToken` for all users to `true`.

2022-09-21 12:29 UTC, vitorhugods requested changes
Really really cool 😎

Just a couple of tiny naming suggestions.

2022-09-21 12:29 UTC, vitorhugods commented on logic/src/commonMain/kotlin/com/wire/kalium/logic/configuration/notification/NotificationTokenRepository.kt
> +data class NotificationToken(val token: String, val transport: String, val senderId: String)
Can we specify what is `senderId`? Is it the client ID? Or User ID?

2022-09-21 12:29 UTC, vitorhugods commented on logic/src/commonMain/kotlin/com/wire/kalium/logic/data/user/UserRepository.kt
> +    suspend fun setUpdateFirebaseTokenFlag(shouldUpdate: Boolean): Either<StorageFailure, Unit>
This Repo already has too many responsibilities.
We could create a `PushTokenRepository` that has these two functions there.

2022-09-21 12:29 UTC, vitorhugods commented on logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/notificationToken/ObserveNotificationTokenUpdating.kt
> +internal interface ObserveNotificationTokenUpdating {
As this is not a UseCase, we can name it like a normal type and not like a function.

```suggestion
internal interface PushTokenUpdater
```

2022-09-21 12:29 UTC, vitorhugods commented on logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/notificationToken/ObserveNotificationTokenUpdating.kt
> +    suspend operator fun invoke()
Perhaps

```suggestion
    suspend fun monitorTokenChanges()
```

This way, the utilisation becomes:

```kotlin
launch {
    val pushTokenUpdater = createPushTokenUpdater()
    pushTokenUpdater.monitorTokenChanges()
}
```

2022-09-21 12:29 UTC, vitorhugods commented on logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/notificationToken/ObserveNotificationTokenUpdating.kt
> +                if (result.isRight()) userRepository.setUpdateFirebaseTokenFlag(false)
Really cool 😎

2022-09-21 12:29 UTC, vitorhugods commented on logic/src/commonMain/kotlin/com/wire/kalium/logic/feature/UserSessionScope.kt
>          }
Maybe we could launch this on its own job, so people don't forget that this operation is long suspending.

```suggestion
        }
        launch {
            observeNotificationTokenUpdating()
        }
```

2022-09-23 14:03 UTC, MohammedMokresh approved these changes
LGTM

2022-09-23 20:51 UTC, vitorhugods approved these changes
🚀👩🏼‍🚀👨🏼‍🚀🧑🏼‍🚀

2022-09-24 09:16 UTC, merged